// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {deepgram} from '../models';

export function Close():Promise<void>;

export function Read():Promise<deepgram.TranscriptionResult>;

export function SendForTranscription(arg1:Array<number>):Promise<void>;
