// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['deepgram']['SpeechToTextController']['Close']();
}

export function Connect() {
  return window['go']['deepgram']['SpeechToTextController']['Connect']();
}

export function Read() {
  return window['go']['deepgram']['SpeechToTextController']['Read']();
}

export function SendForTranscription(arg1) {
  return window['go']['deepgram']['SpeechToTextController']['SendForTranscription'](arg1);
}
