// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['stt']['Deepgram']['Close']();
}

export function Connect() {
  return window['go']['stt']['Deepgram']['Connect']();
}

export function ReadLastTranscription() {
  return window['go']['stt']['Deepgram']['ReadLastTranscription']();
}

export function SendForTranscription(arg1) {
  return window['go']['stt']['Deepgram']['SendForTranscription'](arg1);
}
