// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stt} from '../models';

export function Close():Promise<void>;

export function Connect():Promise<boolean>;

export function ReadLastTranscription():Promise<stt.TranscriptionResult>;

export function SendForTranscription(arg1:Array<number>):Promise<void>;
