// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMessage(arg1, arg2, arg3) {
  return window['go']['services']['ChatService']['AddMessage'](arg1, arg2, arg3);
}

export function Ask(arg1, arg2) {
  return window['go']['services']['ChatService']['Ask'](arg1, arg2);
}

export function GetChatByID(arg1) {
  return window['go']['services']['ChatService']['GetChatByID'](arg1);
}

export function GetChatWithMessages(arg1) {
  return window['go']['services']['ChatService']['GetChatWithMessages'](arg1);
}

export function GetChatsWithoutMessages() {
  return window['go']['services']['ChatService']['GetChatsWithoutMessages']();
}

export function New(arg1) {
  return window['go']['services']['ChatService']['New'](arg1);
}
