// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function AddMessage(arg1:number,arg2:string,arg3:string):Promise<void>;

export function Ask(arg1:number,arg2:string):Promise<Array<chat.Message>>;

export function DeleteChat(arg1:number):Promise<void>;

export function GetChatByID(arg1:number):Promise<chat.Chat>;

export function GetChatWithMessages(arg1:number):Promise<chat.Chat>;

export function GetChatsWithoutMessages():Promise<Array<chat.Chat>>;

export function New(arg1:string):Promise<chat.Chat>;
